name: ROS 1 CI

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
jobs:
  test_environment-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - kinetic
          - melodic
          - noetic
        include:
            # Kinetic Kame (May 2016 - May 2021)
          - docker_image: ubuntu:xenial
            ros_distribution: kinetic
            ros_version: 1
            # Melodic Morenia (May 2018 - May 2023)
          - docker_image: ubuntu:bionic
            ros_distribution: melodic
            ros_version: 1
            # Noetic Ninjemys (May 2020 - May 2025)
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/peak_cam
      - name: install IDS peak dependencies
        run: sudo apt-get install libqt5core5a libqt5gui5 libqt5widgets5 libqt5quick5 qml-module-qtquick-window2 qml-module-qtquick2 qtbase5-dev qtdeclarative5-dev qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-layouts libusb-1.0-0
      - name: install IDS peak
        run: dpkg -i src/peak_cam/ids_peak/ids-peak-linux-x86-1.2.0.1-64.deb
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          install-connext: false
          use-ros2-testing: false
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
         package-name: peak_cam
         target-ros1-distro: ${{ matrix.ros_distribution }}
         vcs-repo-file-url: ""
